---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "/**/*.{astro,ts}"
  templates:
  - page
- type: directory
  path: src/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
upload_dir: Mykal Codes
public_path: https://res.cloudinary.com/mykalcodes/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist/
  install_dependencies_command: npm install
  preview_docker_image: node:16.0-buster-slim
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
